export const categoriesIds = {
  "Mountain Bikes": 1,
  "Road Bikes": 2,
  "Touring Bikes": 3,
  Handlebars: 4,
  "Bottom Brackets": 5,
  Brakes: 6,
  Chains: 7,
  Cranksets: 8,
  Derailleurs: 9,
  Forks: 10,
  Headsets: 11,
  "Mountain Frames": 12,
  Pedals: 13,
  "Road Frames": 14,
  Saddles: 15,
  "Touring Frames": 16,
  Wheels: 17,
  "Bib-Shorts": 18,
  Caps: 19,
  Gloves: 20,
  Jerseys: 21,
  Shorts: 22,
  Socks: 23,
  Tights: 24,
  Vests: 25,
  "Bike Racks": 26,
  "Bike Stands": 27,
  "Bottles and Cages": 28,
  Cleaners: 29,
  Fenders: 30,
  Helmets: 31,
  "Hydration Packs": 32,
  Lights: 33,
  Locks: 34,
  Panniers: 35,
  Pumps: 36,
  "Tires and Tubes": 37,
};

export const categories = ["Bikes", "Components", "Clothing", "Accessories"];

export const subCategories = {
  Bikes: ["Mountain Bikes", "Road Bikes", "Touring Bikes"],
  Components: [
    "Handlebars",
    "Bottom Brackets",
    "Brakes",
    "Chains",
    "Cranksets",
    "Derailleurs",
    "Forks",
    "Headsets",
    "Mountain Frames",
    "Pedals",
    "Road Frames",
    "Saddles",
    "Touring Frames",
    "Wheels",
  ],
  Clothing: [
    "Bib-Shorts",
    "Caps",
    "Gloves",
    "Jerseys",
    "Shorts",
    "Socks",
    "Tights",
    "Vests",
  ],
  Accessories: [
    "Bike Racks",
    "Bike Stands",
    "Bottles and Cages",
    "Cleaners",
    "Fenders",
    "Helmets",
    "Hydration Packs",
    "Lights",
    "Locks",
    "Panniers",
    "Pumps",
    "Tires and Tubes",
  ],
};
