export const categories = ["Bikes", "Components", "Clothing", "Accessories"];

export const subCategories = {
  Bikes: ["Mountain Bikes", "Road Bikes", "Touring Bikes"],
  Components: [
    "Handlebars",
    "Bottom Brackets",
    "Brakes",
    "Chains",
    "Cranksets",
    "Derailleurs",
    "Forks",
    "Headsets",
    "Mountain Frames",
    "Pedals",
    "Road Frames",
    "Saddles",
    "Touring Frames",
    "Wheels",
  ],
  Clothing: [
    "Bib-Shorts",
    "Caps",
    "Gloves",
    "Jerseys",
    "Shorts",
    "Socks",
    "Tights",
    "Vests",
  ],
  Accessories: [
    "Bike Racks",
    "Bike Stands",
    "Bottles and Cages",
    "Cleaners",
    "Fenders",
    "Helmets",
    "Hydration Packs",
    "Lights",
    "Locks",
    "Panniers",
    "Pumps",
    "Tires and Tubes",
  ],
};
