export const departmentsIds = {
  Engineering: 1,
  "Tool Design": 2,
  Sales: 3,
  Marketing: 4,
  Purchasing: 5,
  "Research and Development": 6,
  Production: 7,
  "Production Control": 8,
  "Human Resources": 9,
  Finance: 10,
  "Information Services": 11,
  "Document Control": 12,
  "Quality Assurance": 13,
  "Facilities and Maintenance": 14,
  "Shipping and Receiving": 15,
  Executive: 16,
};

export const departments = [
  "Engineering",
  "Tool Design",
  "Sales",
  "Marketing",
  "Purchasing",
  "Research and Development",
  "Production",
  "Production Control",
  "Human Resources",
  "Finance",
  "Information Services",
  "Document Control",
  "Quality Assurance",
  "Facilities and Maintenance",
  "Shipping and Receiving",
  "Executive",
];
